### ISSUE TITLE
Can't read data from the game

### ISSUE THREAD

**Issue by hzy46** [metal-crow/Dark-Souls-PvP-AI#13]
The CT table [here](https://github.com/metal-crow/Dark-Souls-PvP-AI/blob/master/DARKSOULS_AI_Help.CT) doesn't seem to work. The data are all ??? after attaching to the game:
![image](https://user-images.githubusercontent.com/7499023/27261715-777db4ac-547b-11e7-9cd9-3d715d7732c4.png)

And the CT table from  [Technojacker's ](https://drive.google.com/drive/folders/0B_f11g1DlLhDV1RfV0VSdnBfOVE?usp=sharing) works properly for me:
![image](https://user-images.githubusercontent.com/7499023/27261723-a1c2fdc6-547b-11e7-82f6-159314dd085a.png)

How can I fix this problem? Thanks!

**Comment by metal-crow** [comment]
Hmm, that's odd. A lot of those pointers are pulled directly from Technojackers table, including the cam x pointer (for the ones below the Infinite Durability script, while its also odd they don't work, they're not necessary for the AI. I just had them in during testing). 

Can you check if the camera x coordinates on Technojackers (or maybe [Phokzs](https://github.com/saeshyl/reCode/blob/master/Dark%20Souls/Phokz.CT), forget what table i based this off of) table works? It should be under Camera Coordinates or something. If so, just use that in the meantime (at position 3.141592)

I'd do some debugging myself, but I'm on a vacation rn, so I'll fix this permanently in a week or so.

**Comment by metal-crow** [comment]
Ah yep, it's definitely a bug on my part. Technojacker's table has the camera rotation variables under `Camera Control Coords` and `Lock Camera Rotation`, but it's using a dynamic variable or something from the script, which i must have not replicated correctly in my direct pointer (I just used pointer scanner or something).

Just pushed a commit that should fix it (it's all encapsulated in the lock camera script via code injection now), let me know if that fixes your problem.

**Comment by metal-crow** [comment]
I'll just close this issue rn, if you still have trouble feel free to open a new one!
